version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123password
    ports:
      - 27017:27017
    volumes:
      - .docker/mongodb:/data/db
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis :/data
    restart: always

volumes:
  mongodb_data_container:
